name: "ConflictBot"
description: "Check for conflicts against other open PRs"
branding:
  icon: align-center
  color: yellow
inputs:
  github-token:
    description: "GitHub token"
    required: true
  debug:
    description: "Toggle debug level logging"
    required: false
  main-branch:
    description: "Name of main branch (defaults to 'main')"
    required: false
  quiet:
    description: "Only request reviews without commenting (defaults to 'false')"
    required: false
runs:
  using: node20
  main: dist/index.js
